### ISSUE TITLE
Broker loads max 50 workitems

### ISSUE THREAD

**Issue by dhommen** [truzzt/FederatedCatalog#47]
# Bug Report

## Describe the Bug
The broker loads max of 50 workitems to crawl

### Expected Behavior
The broker should load all known nodes as workitems to be crawled

### Observed Behavior
The broker only loads max 50 workitems to be crawled

## Steps to Reproduce
1. Setup Broker
2. Register 50+ connectors
3. Wait for crawler to start

## Context Information
- Used version ghcr.io/truzzt/federated-catalog:image-v0.0.4

## Detailed Description
![Screenshot 2023-07-12 at 17 05 07](https://github.com/truzzt/FederatedCatalog/assets/75446820/47f843b1-b3b8-4cc4-ae6c-fe5dc6da351b)
![Screenshot 2023-07-12 at 17 04 34](https://github.com/truzzt/FederatedCatalog/assets/75446820/42ec605c-cc63-4400-abb2-8a6517f75472)

## Possible Implementation
_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

**Comment by jannotti-glaucio** [comment]
The problem is related to the query of `FederatedCacheNode` used to load the work items to be processed by the crawler.
The number of created crawler instances will equal the number of work items and the SQL implementation of the `FederatedCacheNode` interface is returning no more than 50 records. 

The SQL query built on `SqlFederatedNodeDirectory.getAll()` method is not defining the query limit property and the `QuerySpec` class is using its default limit value of 50:

https://github.com/truzzt/FederatedCatalog/blob/f3bb0da194441d70677d982908dc2cbee4eec34c/extensions/store/fcc-node-directory-sql/src/main/java/de/truzzt/edc/extension/catalog/directory/sql/SqlFederatedNodeDirectory.java#L54

https://github.com/eclipse-edc/Connector/blob/a6fdb2a0b4360629ec562e11ae19d077162200b7/spi/common/core-spi/src/main/java/org/eclipse/edc/spi/query/QuerySpec.java#L36

To solve the problem we have three possible solutions:

1 - Create an environment variable to configure the max number of 'FederatedCacheNode' returns in the `getAll()` method and use this variable value as the query limit.

2 - Define a fixed value to the query limit. We can choose a value high enough to support the max number of registered connectors in all known scenarios.

3 - Create a new `FederatedNodeDirectory.getAll()` method in our FederatedNodeDirectory interface, receiving as a parameter the max number of items to return. After that, we can use the value of the environment variable `EDC_CATALOG_CACHE_PARTITION_NUM_CRAWLERS`  as the method parameter, returning always a number of work items less of equals the allowed max number of crawlers to be created:

https://github.com/truzzt/FederatedCatalog/blob/f3bb0da194441d70677d982908dc2cbee4eec34c/spi/federated-catalog-spi/src/main/java/org/eclipse/edc/catalog/spi/directory/FederatedCacheNodeDirectory.java#L5

Please let me know the solution to implement.

**Comment by schoenenberg** [comment]
Very nice description of the issue 👍 

As discussed in the Daily please fix it for now with the solution 2 and please set it to 5000. When we switch to a newer version of the EDC, we can think about making it configurable similar to this: https://github.com/eclipse-edc/Connector/issues/3044
